[main]
font=JetBrainsMono Nerd Font:size=12
prompt="❯ "
terminal=foot
# Dimensions: width is in characters, not pixels
width=30
horizontal-pad=20
vertical-pad=15
inner-pad=10

# Radius for that modern look
border-radius=15
border-width=2

[colors]
# Pywal placeholders
background=2f1918ff
text=eddfe2ff
match=D099AEff
selection=a59c9eff
selection-text=eddfe2ff
selection-match=D099AEff
border=CAB1CFff

[border]
width=2
radius=15
